# All values within {}'s must be replaced by the user
# {YYYYMMDD} ~ 20190530
# {expid} ~ e5303_m21c_jan18
# {timeseries_src_dir} ~ the full path to the directory src directory (i.e. $NOBACKUP/pyradmon/offline/timeseries/src/)
# {expname} ~ can be anything, ex: m21c_radmon
################################
#obsdatain: demo/gdas1.200101.t00z.prepbufr
#obsdataout:
#yaml_template: 
################################

################################
obsdatain: 'demo/gdas1.200101.t00z.prepbufr'
obsdataout: './gdas1.200101.t00z.bufr_ncep_rtma_prepbufr_adpupa.nc4'
yaml_template: 'demo/bufr_ncep_rtma_prepbufr_adpupa.yaml'
################################



